### ISSUE TITLE
user_switching_clear_olduser_cookie() causes fatal error with WooCommerce

### ISSUE THREAD

**Issue by joekissell** [johnbillion/user-switching#142]
Since installing version 1.9.0, I've been getting grumpy customers reporting to me that when they place an order in my WooCommerce store, the final page (which appears after payment processing and is supposed to show their order confirmation) displays a WordPress fatal error message instead. My logs contain many instances of this:

`
2024-12-01T04:31:31+00:00 CRITICAL Uncaught TypeError: user_switching_clear_olduser_cookie(): Argument #1 ($clear_all) must be of type bool, null given, called in /var/www/html/tc/wp-includes/class-wp-hook.php on line 326 and defined in /var/www/html/tc/wp-content/plugins/user-switching/user-switching.php:1418 CONTEXT: {"error":{"type":1,"file":"/var/www/html/tc/wp-content/plugins/user-switching/user-switching.php","line":1418},"remote-logging":true,"backtrace":["","#0 /var/www/html/tc/wp-includes/class-wp-hook.php(326): user_switching_clear_olduser_cookie(NULL)","#1 /var/www/html/tc/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)","#2 /var/www/html/tc/wp-includes/plugin.php(517): WP_Hook->do_action(Array)","#3 /var/www/html/tc/wp-content/plugins/takecontrol/takecontrol.php(1203): do_action('wp_login', NULL, NULL)","#4 /var/www/html/tc/wp-includes/class-wp-hook.php(324): thankyou_login(1051740)","#5 /var/www/html/tc/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)","#6 /var/www/html/tc/wp-includes/plugin.php(517): WP_Hook->do_action(Array)","#7 /var/www/html/tc/wp-content/plugins/woocommerce/templates/checkout/thankyou.php(28): do_action('woocommerce_bef...', 1051740)","#8 /var/www/html/tc/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/v...')","#9 /var/www/html/tc/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php(335): wc_get_template('checkout/thanky...', Array)","#10 /var/www/html/tc/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php(65): WC_Shortcode_Checkout::order_received(1051740)","#11 /var/www/html/tc/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(72): WC_Shortcode_Checkout::output(Array)","#12 /var/www/html/tc/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(95): WC_Shortcodes::shortcode_wrapper(Array, Array)","#13 /var/www/html/tc/wp-includes/shortcodes.php(434): WC_Shortcodes::checkout(Array, '', 'woocommerce_che...')","#14 [internal function]: do_shortcode_tag(Array)","#15 /var/www/html/tc/wp-includes/shortcodes.php(273): preg_replace_callback('/\\[(\\[?)(woocom...', 'do_shortcode_ta...', '[woocommerce_ch...')","#16 /var/www/html/tc/wp-includes/class-wp-hook.php(324): do_shortcode('[woocommerce_ch...')","#17 /var/www/html/tc/wp-includes/plugin.php(205): WP_Hook->apply_filters('[woocommerce_ch...', Array)","#18 /var/www/html/tc/wp-includes/post-template.php(256): apply_filters('the_content', '[woocommerce_ch...')","#19 /var/www/html/tc/wp-content/themes/storefront/inc/storefront-template-functions.php(352): the_content()","#20 /var/www/html/tc/wp-includes/class-wp-hook.php(324): storefront_page_content('')","#21 /var/www/html/tc/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)","#22 /var/www/html/tc/wp-includes/plugin.php(517): WP_Hook->do_action(Array)","#23 /var/www/html/tc/wp-content/themes/storefront/content-page.php(18): do_action('storefront_page')","#24 /var/www/html/tc/wp-includes/template.php(812): require('/v...')","#25 /var/www/html/tc/wp-includes/template.php(745): load_template('/v...', false, Array)","#26 /var/www/html/tc/wp-includes/general-template.php(206): locate_template(Array, true, false, Array)","#27 /var/www/html/tc/wp-content/themes/storefront/page.php(24): get_template_part('content', 'page')","#28 /var/www/html/tc/wp-includes/template-loader.php(106): include('/v...')","#29 /var/www/html/tc/wp-blog-header.php(19): require_once('/v...')","#30 /var/www/html/tc/index.php(17): require('/v...')","#31 {main}","thrown"]}
`

It appears to have to do with the change from this:

`function user_switching_clear_olduser_cookie( $clear_all = true ) {`

to this:

`function user_switching_clear_olduser_cookie( bool $clear_all = true ): void {`

Any advice would be appreciated.

**Comment by johnbillion** [comment]
Thanks for the report! This is indeed a bug in User Switching.

**Comment by johnbillion** [comment]
@joekissell Looking at the stack trace in your report, there appears to also be a bug in the "takecontrol" plugin on your site. It's calling `do_action('wp_login', NULL, NULL)` which is incorrect because the `wp_login` action expects a user ID.

Thirdly, what tool are you using for your stack trace logging? It's not a format I've seen before.

**Comment by joekissell** [comment]
Thanks. The stack trace is the WooCommerce default. As for the takecontrol plugin, that's my code, and errors are absolutely possible (though I didn't experience this problem with version 1.8.0 of User Switching). That `do_action()` _shouldn't_ be sending NULLs, and I have a suspicion as to why it's doing so sometimes, which I'll investigate. Thanks for pointing that out; I had entirely overlooked it.

**Comment by johnbillion** [comment]
It looks like that `null` value for the `wp_login` action is actually the cause of the fatal error on your site. Weirdly other non-boolean types are accepted for a boolean parameter, but `null` isn't one of them.

Ref: https://3v4l.org/QlMMm

**Comment by joekissell** [comment]
Interesting. I've added some logging to see if I can track that down. It happens only occasionally, so I have to wait until the right conditions show up to catch it. Nevertheless, the error began only after I installed 1.9.0, so it seems as though there's still something not quite right in User Switching.

**Comment by johnbillion** [comment]
Yeah the underlying issue is that User Switching passes the first parameter of the `wp_login` and `wp_logout` action to the `user_switching_clear_olduser_cookie()` method, which isn't correct because its value is an integer (for the user ID), not a boolean. But it seems that `null` is the only value which actually triggers a fatal.

I'm working on the fix.

**Comment by joekissell** [comment]
Groovy, thanks. I'm hot on the trail of that `null` on my side.

**Comment by joekissell** [comment]
As a band-aid, I've told my plugin that if it encounters `null` for a login or user ID to set them to `false` instead; still trying to understand what circumstances could lead to `null` in the first place, but that's my problem :-).

**Comment by joekissell** [comment]
Found it. It was a race condition that occurred only when someone placed an order who didn't already have an account with us. WooCommerce creates an account automatically at the end of the order process, but sometimes it does so a fraction of a second after my plugin calls `do_action('wp_login')`, and in that brief period, the user doesn't have a user ID yet, so there's nothing to pass on. So now I'm checking to see if we know the user ID at that split second, and if we don't, we now sleep for a second to allow that process to catch up.

**Comment by joekissell** [comment]
> Closed #142 as completed via #143.
Thanks very much!

Joe
