### ISSUE TITLE
Running into an issue where User-switching interferes with Woocommerce

### ISSUE THREAD

**Issue by giftgator** [johnbillion/user-switching#41]
When ever we leave user switching enabled and try add a product to cart (which fails) we see this error in the php log:

```
[02-Jun-2019 17:22:16 UTC] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to user_switching::filter_user_has_cap() must be of the type array, string given, called in /home/okanag8/public_html/wp-includes/class-wp-hook.php on line 286 and defined in /home/okanag8/public_html/wp-content/plugins/user-switching/user-switching.php:817
Stack trace:
#0 /home/okanag8/public_html/wp-includes/class-wp-hook.php(286): user_switching->filter_user_has_cap(Array, 'edit_other_vend...', Array, Object(WP_User))
#1 /home/okanag8/public_html/wp-includes/plugin.php(208): WP_Hook->apply_filters(Array, Array)
#2 /home/okanag8/public_html/wp-includes/class-wp-user.php(768): apply_filters('user_has_cap', Array, 'edit_other_vend...', Array, Object(WP_User))
#3 /home/okanag8/public_html/wp-includes/capabilities.php(649): WP_User->has_cap('edit_post', 103182)
#4 /home/okanag8/public_html/wp-content/plugins/js_composer/include/classes/core/access/abstract-class-vc-access.php(105): current_user_can('edit_post', 103182)
#5 /home/okanag8/public_html/wp-content/plugins/js_comp in /home/okanag8/public_html/wp-content/plugins/user-switching/user-switching.php on line 817
```

**Comment by johnbillion** [comment]
Your stack trace tells me there's a bug in the `js_composer` plugin. For some reason it's manually calling `apply_filters('user_has_cap' ...` and it's doing so with an incorrect third parameter. You should contact the author of that plugin and inform them of the problem.

**Comment by giftgator** [comment]
Thanks, sorry to have bothered you. I realized a little later the wpbakery js_comp reference. Will have that checked. Keep up the good work.
